######################################################################
# Automatically generated by qmake (2.01a) Sa 22. Dez 19:00:33 2007
######################################################################

TEMPLATE = app
TARGET = latt
DEPENDPATH += .
INCLUDEPATH += .
QT += opengl

# Input
HEADERS += window.h gl.h detector.h
SOURCES += main.cpp window.cpp gl.cpp detector.cpp
RESOURCES += icons.qrc

